name: flutter_built_redux_counter
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  built_redux: ">=6.1.1 <8.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
#  build_runner: ">=0.6.0 <0.11.0"
  built_value: ">=5.0.0 <7.0.0"
  built_value_generator: ">=5.0.0 <7.0.0"
  build_runner: 1.2.8
flutter:

  uses-material-design: true