name: flutter_built_redux_counter
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  built_redux: ">=6.1.1 <8.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  built_value: ">=5.0.0 <7.0.0"
  built_value_generator: ">=5.0.0 <7.0.0"
  build_runner: 1.2.8
  # ⚠️ ⚠️ ⚠️
  # 增加redux action后需要执行下面的命令，自动更新对应的 *.g.dart 文件
  # flutter pub pub run build_runner build --delete-conflicting-outputs
  # *.g.dart 文件类似iOS的分类，用于实现redux相关的具体实现

flutter:

  uses-material-design: true